const json = {
  tag: "div",
  attrs: { className: "main-container" },
  style: { "background-color": "#fff", padding: "15px" },
  children: [
    {
      tag: "div",
      name: "页面内容",
      attrs: { className: "content-174" },
      style: {},
      children: [
        {
          tag: "div",
          name: "矩形",
          attrs: { className: "content-347" },
          style: {
            "border-radius": "4px",
            background: "rgba(255, 255, 255, 1.0)",
            "background-blend-mode": "normal",
            "box-shadow": "0px 2px 12px 0px rgba(30, 33, 47, 0.1)",
            "word-break": "break-all",
            height: "814px",
          },
          children: [
            {
              tag: "div",
              name: "到期证书",
              style: {
                "word-break": "break-all",
                color: "rgba(80, 85, 104, 1.0)",
                "font-size": "16px",
                height: "auto",
                padding: "16px 20px 0px 20px",
              },
              attrs: { className: "text-style-348" },
              children: "到期证书",
              frame: {
                _class: "rect",
                constrainProportions: false,
                height: 16,
                width: 64,
                x: 20,
                y: 16,
                l: 20,
                r: 20,
                realWidth: 1160,
              },
            },
            {
              tag: "div",
              name: "路径",
              attrs: { className: "content-350" },
              style: {
                "border-radius": "0px",
                background: "rgba(229, 231, 237, 1.0)",
                "background-blend-mode": "normal",
                "word-break": "break-all",
                height: "1px",
                margin: "14px 0px 0px 0px",
                width: "100%",
              },
              children: [],
              frame: {
                _class: "rect",
                constrainProportions: false,
                height: 1,
                width: 1200,
                x: 0,
                y: 46,
                l: 0,
                r: 0,
              },
            },
            {
              tag: "Form",
              ident: "Form",
              attrs: { initialValues: {}, scrollToFirstError: true },
              style: {},
              children: [
                {
                  tag: "div",
                  name: "表单",
                  attrs: { className: "content-386" },
                  style: {
                    margin: "20px 20px 0px 20px",
                    width: "96.67%",
                    "margin-top": 0,
                  },
                  children: [
                    {
                      tag: "div",
                      attrs: { className: "grid-style-440" },
                      children: [
                        {
                          tag: "div",
                          children: [
                            {
                              tag: "div",
                              name: "页面内容",
                              attrs: { className: "content-392" },
                              style: {},
                              children: [
                                {
                                  tag: "Form.Item",
                                  ident: "FormItem",
                                  attrs: {
                                    name: "name",
                                    colon: false,
                                    className: "",
                                    label: {
                                      tag: "span",
                                      value: "证书名称:",
                                      type: "form",
                                      style: { fontSize: "14px" },
                                    },
                                  },
                                  contentWidth: 268,
                                  elementWidth: 200,
                                  children: [
                                    {
                                      tag: "Input",
                                      ident: "Input",
                                      attrs: {
                                        placeholder: "请输入",
                                        className: "input-style-393",
                                      },
                                      style: { width: "200px" },
                                    },
                                  ],
                                  frame: {
                                    _class: "rect",
                                    constrainProportions: false,
                                    height: 30,
                                    width: 268,
                                    x: 0,
                                    y: 0,
                                    l: 0,
                                    r: 0,
                                  },
                                },
                              ],
                              frame: { x: 0, y: 0, width: 307 },
                            },
                          ],
                        },
                        {
                          tag: "div",
                          children: [
                            {
                              tag: "div",
                              name: "页面内容",
                              attrs: { className: "content-399" },
                              style: {},
                              children: [
                                {
                                  tag: "Form.Item",
                                  ident: "FormItem",
                                  attrs: {
                                    name: "name",
                                    colon: false,
                                    className: "",
                                    label: {
                                      tag: "span",
                                      value: "证书ID:",
                                      type: "form",
                                      style: { fontSize: "14px" },
                                    },
                                  },
                                  contentWidth: 253,
                                  elementWidth: 200,
                                  children: [
                                    {
                                      tag: "Input",
                                      ident: "Input",
                                      attrs: {
                                        placeholder: "请输入",
                                        className: "input-style-400",
                                      },
                                      style: { width: "200px" },
                                    },
                                  ],
                                  frame: {
                                    _class: "rect",
                                    constrainProportions: false,
                                    height: 30,
                                    width: 253,
                                    x: 0,
                                    y: 0,
                                    l: 0,
                                    r: 0,
                                  },
                                },
                              ],
                              frame: { x: 0, y: 0, width: 307 },
                            },
                          ],
                        },
                        {
                          tag: "div",
                          children: [
                            {
                              tag: "div",
                              name: "页面内容",
                              attrs: { className: "content-406" },
                              style: {},
                              children: [
                                {
                                  tag: "Form.Item",
                                  ident: "FormItem",
                                  attrs: {
                                    name: "name",
                                    colon: false,
                                    className: "",
                                    label: {
                                      tag: "span",
                                      value: "申请人:",
                                      type: "form",
                                      style: { fontSize: "14px" },
                                    },
                                  },
                                  contentWidth: 254,
                                  elementWidth: 200,
                                  children: [
                                    {
                                      tag: "Input",
                                      ident: "Input",
                                      attrs: {
                                        placeholder: "请输入完整的ip和port",
                                        className: "input-style-407",
                                      },
                                      style: { width: "200px" },
                                    },
                                  ],
                                  frame: {
                                    _class: "rect",
                                    constrainProportions: false,
                                    height: 30,
                                    width: 254,
                                    x: 0,
                                    y: 0,
                                    l: 0,
                                    r: 0,
                                  },
                                },
                              ],
                              frame: { x: 0, y: 0, width: 307 },
                            },
                          ],
                        },
                        {
                          tag: "div",
                          children: [
                            {
                              tag: "div",
                              name: "页面内容",
                              attrs: { className: "content-414" },
                              style: {},
                              children: [
                                {
                                  tag: "Form.Item",
                                  ident: "FormItem",
                                  attrs: {
                                    name: "name",
                                    colon: false,
                                    className: "",
                                    label: {
                                      tag: "span",
                                      value: "部署位置:",
                                      type: "form",
                                      style: { fontSize: "14px" },
                                    },
                                  },
                                  contentWidth: 268,
                                  elementWidth: 200,
                                  children: [
                                    {
                                      tag: "Select",
                                      ident: "Select",
                                      attrs: {
                                        placeholder: "全部",
                                        allowClear: true,
                                        showSearch: true,
                                        className: "select-style-415",
                                      },
                                      style: { width: "200px" },
                                    },
                                  ],
                                  frame: {
                                    _class: "rect",
                                    constrainProportions: false,
                                    height: 30,
                                    width: 268,
                                    x: 0,
                                    y: 0,
                                    l: 0,
                                    r: 0,
                                  },
                                },
                              ],
                              frame: { x: 0, y: 0, width: 307 },
                            },
                          ],
                        },
                        {
                          tag: "div",
                          children: [
                            {
                              tag: "div",
                              name: "页面内容",
                              attrs: { className: "content-421" },
                              style: {},
                              children: [
                                {
                                  tag: "Form.Item",
                                  ident: "FormItem",
                                  attrs: {
                                    name: "name",
                                    colon: false,
                                    className: "",
                                    label: {
                                      tag: "span",
                                      value: "域名:",
                                      type: "form",
                                      style: { fontSize: "14px" },
                                    },
                                  },
                                  contentWidth: 240,
                                  elementWidth: 200,
                                  children: [
                                    {
                                      tag: "Input",
                                      ident: "Input",
                                      attrs: {
                                        placeholder: "请输入",
                                        className: "input-style-422",
                                      },
                                      style: { width: "200px" },
                                    },
                                  ],
                                  frame: {
                                    _class: "rect",
                                    constrainProportions: false,
                                    height: 30,
                                    width: 240,
                                    x: 28,
                                    y: 10,
                                    l: 28,
                                    r: 28,
                                  },
                                },
                              ],
                              frame: { x: 0, y: 0, width: 307 },
                            },
                          ],
                        },
                        {
                          tag: "div",
                          children: [
                            {
                              tag: "div",
                              name: "页面内容",
                              attrs: { className: "content-429" },
                              style: {},
                              children: [
                                {
                                  tag: "Form.Item",
                                  ident: "FormItem",
                                  attrs: {
                                    name: "name",
                                    colon: false,
                                    className: "",
                                    label: {
                                      tag: "span",
                                      value: "状态:",
                                      type: "form",
                                      style: { fontSize: "14px" },
                                    },
                                  },
                                  contentWidth: 240,
                                  elementWidth: 200,
                                  children: [
                                    {
                                      tag: "Select",
                                      ident: "Select",
                                      attrs: {
                                        placeholder: "全部",
                                        allowClear: true,
                                        showSearch: true,
                                        className: "select-style-430",
                                      },
                                      style: { width: "200px" },
                                    },
                                  ],
                                  frame: {
                                    _class: "rect",
                                    constrainProportions: false,
                                    height: 30,
                                    width: 240,
                                    x: 13,
                                    y: 10,
                                    l: 13,
                                    r: 13,
                                  },
                                },
                              ],
                              frame: { x: 0, y: 0, width: 307 },
                            },
                          ],
                        },
                        { tag: "div", children: [] },
                        {
                          tag: "div",
                          children: [
                            {
                              tag: "div",
                              name: "页面内容",
                              attrs: { className: "content-434" },
                              style: {},
                              children: [
                                {
                                  tag: "div",
                                  ident: "div",
                                  name: "分组",
                                  style: {
                                    display: "flex",
                                    padding: "10px 0px 0px 24%",
                                  },
                                  attrs: { className: "div-style-437" },
                                  children: [
                                    {
                                      tag: "Button",
                                      ident: "Button",
                                      attrs: {
                                        ghost: false,
                                        className: "btn-style-438",
                                      },
                                      style: { width: "auto" },
                                      children: "重置",
                                      frame: {
                                        _class: "rect",
                                        constrainProportions: false,
                                        height: 30,
                                        width: 74,
                                        x: 0,
                                        y: 0,
                                        l: 0,
                                        r: 0,
                                      },
                                    },
                                    {
                                      tag: "Button",
                                      ident: "Button",
                                      attrs: {
                                        ghost: false,
                                        type: "primary",
                                        className: "btn-style-439",
                                      },
                                      style: {
                                        width: "auto",
                                        margin: "0px 0px 0px 16px",
                                      },
                                      children: "查询",
                                      frame: {
                                        _class: "rect",
                                        constrainProportions: false,
                                        height: 30,
                                        width: 74,
                                        x: 90,
                                        y: 0,
                                        l: 90,
                                        r: 90,
                                      },
                                    },
                                  ],
                                  frame: {
                                    x: 75,
                                    y: 10,
                                    height: 30,
                                    l: 75,
                                    r: 0,
                                    width: 307,
                                    _class: "rect",
                                    constrainProportions: false,
                                    realWidth: 232,
                                  },
                                },
                              ],
                              frame: { x: 0, y: 0, width: 307 },
                            },
                          ],
                        },
                      ],
                      style: {
                        display: "grid",
                        "grid-template-rows": "repeat(2, 50%)",
                        "grid-template-columns": "repeat(4, 25%)",
                      },
                      frame: {
                        _class: "rect",
                        constrainProportions: false,
                        height: 80,
                        width: 1160,
                        x: 0,
                        y: 0,
                        l: 0,
                        r: 0,
                      },
                    },
                  ],
                },
              ],
              frame: {
                _class: "rect",
                constrainProportions: false,
                height: 80,
                width: 1160,
                x: 20,
                y: 67,
                l: 20,
                r: 20,
              },
            },
            {
              tag: "Table",
              ident: "Table",
              attrs: {
                columns: [
                  { title: "ID", dataIndex: "name_0", key: "name_0" },
                  { title: "证书名称", dataIndex: "name_1", key: "name_1" },
                  { title: "域名", dataIndex: "name_2", key: "name_2" },
                  { title: "申请人", dataIndex: "name_3", key: "name_3" },
                  { title: "申请部门", dataIndex: "name_4", key: "name_4" },
                  { title: "状态", dataIndex: "name_5", key: "name_5" },
                  { title: "申请时间", dataIndex: "name_6", key: "name_6" },
                  { title: "部署位置", dataIndex: "name_7", key: "name_7" },
                  { title: "订单号", dataIndex: "name_8", key: "name_8" },
                  { title: "外部订单号", dataIndex: "name_9", key: "name_9" },
                  { title: "供应商", dataIndex: "name_10", key: "name_10" },
                  { title: "剩余有效期", dataIndex: "name_11", key: "name_11" },
                  { title: "操作", dataIndex: "name_12", key: "name_12" },
                ],
                dataSource: [
                  {
                    name_0: "1",
                    name_1: "zk-test",
                    name_2: "btlsys.xiaoju.com",
                    name_4: "运维部",
                    name_6: "2021.09.05 15:30",
                    name_7: "接入层",
                    name_8: "20231117",
                    name_9: "20231117",
                    name_10: "甲方",
                    name_11: "6",
                    name_12: "续费",
                  },
                  {
                    name_0: "1",
                    name_1: "zk-test",
                    name_2: "btlsys.xiaoju.com",
                    name_4: "运维部",
                    name_6: "2021.09.05 15:30",
                    name_7: "接入层",
                    name_8: "20231117",
                    name_9: "20231117",
                    name_10: "甲方",
                    name_11: "20",
                    name_12: "续费",
                  },
                  {
                    name_0: "1",
                    name_1: "zk-test",
                    name_2: "btlsys.xiaoju.com",
                    name_4: "运维部",
                    name_6: "2021.09.05 15:30",
                    name_7: "接入层",
                    name_8: "220231117",
                    name_9: "220231117",
                    name_10: "甲方",
                    name_11: "29",
                    name_12: "续费",
                  },
                  {
                    name_0: "1",
                    name_1: "zk-test",
                    name_2: "btlsys.xiaoju.com",
                    name_4: "运维部",
                    name_6: "2021.09.05 15:30",
                    name_7: "接入层",
                    name_8: "20231117",
                    name_9: "20231117",
                    name_10: "甲方",
                    name_11: "59",
                    name_12: "续费",
                  },
                  {
                    name_0: "1",
                    name_1: "zk-test",
                    name_2: "btlsys.xiaoju.com",
                    name_4: "运维部",
                    name_6: "2021.09.05 15:30",
                    name_7: "接入层",
                    name_8: "20231117",
                    name_9: "20231117",
                    name_10: "甲方",
                    name_11: "68",
                    name_12: "续费",
                  },
                ],
                rowKey: "id",
                loading: false,
                size: "small",
                index: 1,
                className: "table-style-626",
                pagination: false,
              },
              style: { margin: "20px 20px 0px 20px", width: "96.67%" },
              frame: {
                _class: "rect",
                constrainProportions: false,
                height: 247,
                width: 1160,
                x: 19.999999999999886,
                y: 167,
                l: 19.999999999999886,
                r: 19.999999999999886,
              },
            },
          ],
          frame: {
            _class: "rect",
            constrainProportions: false,
            height: 814,
            width: 1200,
            x: 0,
            y: 0,
            l: 0,
            r: 0,
          },
        },
      ],
      frame: { x: 0, y: 0, width: 1200 },
    },
  ],
};